<?php

$res = $db->prepare("select ISNULL(COUNT(*),0) AS TOTAL from SALES_CORPORATE.CLIENTE.CLIENTE_CORPORATIVO");
$res->execute();
$total_customer = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL  FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA
 WHERE ESTADO='PENDIENTE DE FACTURACION'");
$res->execute();
$total_solicitudes_pendientes_de_facturar = $res->fetchColumn();


$res = $db->prepare("SELECT 'S/ ' + CONVERT(VARCHAR, CONVERT(VARCHAR, CAST(ISNULL(SUM(IMPORTE_TOTAL),0) AS MONEY), 1)) 
AS TOTAL FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO'");
$res->execute();
$importe_facturado = $res->fetchColumn();

$res = $db->prepare("SELECT 'S/ ' + CONVERT(VARCHAR, CONVERT(VARCHAR, CAST( SUM(ISNULL(IMPORTE_TOTAL-IMPORTE_PAGADO,0)) AS MONEY), 1)) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DEUDA='FACTUARA PENDIENTE DE PAGO'");
$res->execute();
$importe_pendiente_pago = $res->fetchColumn();

$res = $db->prepare("SELECT 'S/ ' + CONVERT(VARCHAR, CONVERT(VARCHAR, CAST( SUM(ISNULL(IMPORTE_TOTAL-IMPORTE_PAGADO,0)) AS MONEY), 1)) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA'
 AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$invoice_vencido_valor = $res->fetchColumn();



?>