<?php
$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='01'");
$res->execute();
$enero_fac_p = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='02'");
$res->execute();
$febrero_fac_p = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='03'");
$res->execute();
$marzo_fac_p = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='04'");
$res->execute();
$abril_fac_p = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='05'");
$res->execute();
$mayo_fac_p = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='06'");
$res->execute();
$junio_fac_p = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='07'");
$res->execute();
$julio_fac_p = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='08'");
$res->execute();
$agosto_fac_p = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='09'");
$res->execute();
$setiembre_fac_p = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='10'");
$res->execute();
$octubre_fac_p = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='11'");
$res->execute();
$noviembre_fac_p = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(SUM(IMPORTE_TOTAL),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO PRÓXIMA A VENCER' and MONTH(FECHA_EMISION_AR) ='12'");
$res->execute();
$diciembre_fac_p = $res->fetchColumn();

?>