<?php
$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='01'");
$res->execute();
$enero = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='02'");
$res->execute();
$febrero = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='03'");
$res->execute();
$marzo = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='04'");
$res->execute();
$abril = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='05'");
$res->execute();
$mayo = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='06'");
$res->execute();
$junio = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='07'");
$res->execute();
$julio = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='08'");
$res->execute();
$agosto = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='09'");
$res->execute();
$setiembre = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='10'");
$res->execute();
$octubre = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='11'");
$res->execute();
$noviembre = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO='FACTURADO' and MONTH(FECHA_EMISION_AR) ='12'");
$res->execute();
$diciembre = $res->fetchColumn();

?>