<?php
$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='01'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$enero_v = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='02'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$febrero_v = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='03'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$marzo_v = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='04'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$abril_v = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='05'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$mayo_v = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='06'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$junio_v = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='07'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$julio_v = $res->fetchColumn();


$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='08'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$agosto_v = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='09'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$setiembre_v = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='10'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$octubre_v = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='11'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$noviembre_v = $res->fetchColumn();

$res = $db->prepare("SELECT ISNULL(COUNT(*),0) AS TOTAL
FROM SALES_CORPORATE.CLIENTE.FACTURACION_CORPORATIVA WHERE ESTADO_DE_FACTURA='FACTURA A CRÉDITO VENCIDA' and MONTH(FECHA_EMISION_AR) ='12'
AND ESTADO_DEUDA NOT IN('FACTUARA PAGADA 100%')");
$res->execute();
$diciembre_v = $res->fetchColumn();

?>